ALTER TABLE agents ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS featured_until TIMESTAMPTZ;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS featured_note TEXT;
