ALTER TABLE agents ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'manual';
ALTER TABLE agents ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ;
