// Base Ecosystem AI Agents Database
// Source: Bankr AI verification + Community research
// Top 100 AI Agents on Base - February 2026
// Last updated: 2026-02-14

export const ETH_PRICE = 2800

export interface Agent {
  id: string
  name: string
  handle: string
  token: string
  category: 'Infrastructure' | 'DeFi' | 'Social' | 'Analytics' | 'Creative' | 'Trading' | 'Gaming' | 'Security'
  description: string
  score: number
  status: 'verified' | 'pending' | 'unverified'
  vouched: number
  reviews: number
  contract?: string
  website?: string
  twitter?: string
  logo: string
  gradient: string
  featured?: boolean
  recentlyAdded?: boolean
  launchPlatform?: 'bankr' | 'clanker' | 'virtuals' | 'other'
  imageUrl?: string | null
  marketCap?: string
  // Team/deployer wallet for Ethos reputation lookup
  teamWallet?: string
}

export const formatVouched = (eth: number) => {
  const usd = eth * ETH_PRICE
  if (usd >= 1000000) return `${eth} ETH / $${(usd / 1000000).toFixed(1)}M`
  if (usd >= 1000) return `${eth} ETH / $${(usd / 1000).toFixed(0)}K`
  return `${eth} ETH / $${usd.toFixed(0)}`
}

export const formatVouchedShort = (eth: number) => {
  const usd = eth * ETH_PRICE
  if (usd >= 1000000) return { eth: `${eth} ETH`, usd: `$${(usd / 1000000).toFixed(1)}M` }
  if (usd >= 1000) return { eth: `${eth} ETH`, usd: `$${(usd / 1000).toFixed(0)}K` }
  return { eth: `${eth} ETH`, usd: `$${usd.toFixed(0)}` }
}

// ══════════════════════════════════════════════════════════════
// TOP 100 AI AGENTS ON BASE - Ranked by Market Cap & Activity
// ══════════════════════════════════════════════════════════════

export const agents: Agent[] = [
  // ═══ TIER 1: INFRASTRUCTURE & PLATFORMS (Top 10) ═══
  {
    id: 'virtuals',
    name: 'Virtuals Protocol',
    handle: '@virtuals_io',
    token: '$VIRTUAL',
    category: 'Infrastructure',
    description: 'Decentralized platform for creating and monetizing AI agents. Tokenized agents, ACP for commerce.',
    score: 99,
    status: 'verified',
    vouched: 139.6,
    reviews: 256,
    contract: '0x0b3e328455c4059eeb9e3f84b5543f74e24e7e1b',
    twitter: 'virtuals_io',
    logo: 'V',
    gradient: 'from-blue-500 to-cyan-500',
    featured: true,
    launchPlatform: 'virtuals',
    marketCap: '$391M'
  },
  {
    id: 'aixbt',
    name: 'AIXBT',
    handle: '@aixbt_agent',
    token: '$AIXBT',
    category: 'Analytics',
    description: 'Market intelligence agent. KOL monitoring, predictions, real-time insights.',
    score: 98,
    status: 'verified',
    vouched: 154.3,
    reviews: 198,
    contract: '0x4f9fd6be4a90f2620860d680c0d4d5fb53d1a825',
    twitter: 'aixbt_agent',
    logo: 'AI',
    gradient: 'from-indigo-500 to-blue-500',
    featured: true,
    launchPlatform: 'virtuals',
    marketCap: '$432M'
  },
  {
    id: 'kite',
    name: 'Kite AI',
    handle: '@kite_ai',
    token: '$KITE',
    category: 'DeFi',
    description: 'AI agent for DeFi and data analysis. Yield optimization, risk assessment.',
    score: 97,
    status: 'verified',
    vouched: 143.6,
    reviews: 187,
    twitter: 'kite_ai',
    logo: 'KT',
    gradient: 'from-sky-500 to-blue-500',
    featured: true,
    launchPlatform: 'other',
    marketCap: '$402M'
  },
  {
    id: 'pippin',
    name: 'Pippin',
    handle: '@pippin_ai',
    token: '$PIPPIN',
    category: 'Social',
    description: 'General multi-task AI agent. Friendly companion with broad capabilities.',
    score: 96,
    status: 'verified',
    vouched: 219.3,
    reviews: 312,
    contract: '0xfd106b77a299bd3b85de8ca4395306965dbfa4c5',
    twitter: 'pippin_ai',
    logo: 'PI',
    gradient: 'from-amber-500 to-yellow-500',
    featured: true,
    launchPlatform: 'other',
    marketCap: '$614M'
  },
  {
    id: 'spectral',
    name: 'Spectral',
    handle: '@Spectral_Labs',
    token: '$SPEC',
    category: 'Infrastructure',
    description: 'Platform for community-owned AI agents. Autonomous agents, no-code builder.',
    score: 95,
    status: 'verified',
    vouched: 89.5,
    reviews: 145,
    twitter: 'Spectral_Labs',
    logo: 'SP',
    gradient: 'from-purple-500 to-pink-500',
    featured: true,
    launchPlatform: 'other'
  },
  {
    id: 'clawd',
    name: 'Clawd OS',
    handle: '@clawd_os',
    token: '$CLAWD',
    category: 'Infrastructure',
    description: 'OS for AI agents, core infrastructure. Agent deployment, multi-chain support.',
    score: 94,
    status: 'verified',
    vouched: 75.2,
    reviews: 128,
    twitter: 'clawd_os',
    logo: 'CL',
    gradient: 'from-orange-500 to-red-500',
    featured: true,
    launchPlatform: 'other'
  },
  {
    id: 'venice',
    name: 'Venice',
    handle: '@AskVenice',
    token: '$VVV',
    category: 'Social',
    description: 'Private AI chat. Uncensored, API access, privacy-focused.',
    score: 93,
    status: 'verified',
    vouched: 36.8,
    reviews: 98,
    twitter: 'AskVenice',
    logo: 'VE',
    gradient: 'from-teal-500 to-cyan-500',
    launchPlatform: 'other',
    marketCap: '$103M'
  },
  {
    id: 'moltbook',
    name: 'Moltbook',
    handle: '@moltbook',
    token: 'N/A',
    category: 'Infrastructure',
    description: 'Social network for agents. Multi-agent hub, API integrations, supports 2M+ agents.',
    score: 92,
    status: 'verified',
    vouched: 45.0,
    reviews: 87,
    twitter: 'moltbook',
    logo: 'M',
    gradient: 'from-teal-500 to-green-500',
    launchPlatform: 'other'
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    handle: '@openclaw_ai',
    token: 'N/A',
    category: 'Infrastructure',
    description: 'Framework for agent societies and testing. QA for apps, agent onboarding.',
    score: 91,
    status: 'verified',
    vouched: 32.0,
    reviews: 76,
    twitter: 'openclaw_ai',
    logo: 'OC',
    gradient: 'from-emerald-500 to-teal-500',
    launchPlatform: 'other'
  },
  {
    id: 'starkbot',
    name: 'Starkbot',
    handle: '@starkbotai',
    token: '$STARKBOT',
    category: 'Infrastructure',
    description: 'Cloud automation for agents. One-click tools, secure infrastructure.',
    score: 90,
    status: 'verified',
    vouched: 28.5,
    reviews: 65,
    twitter: 'starkbotai',
    logo: 'S',
    gradient: 'from-slate-500 to-gray-500',
    launchPlatform: 'other'
  },

  // ═══ TIER 2: TRADING & DEFI AGENTS (11-30) ═══
  {
    id: 'bankr',
    name: 'Bankr',
    handle: '@bankrbot',
    token: '$BNKR',
    category: 'DeFi',
    description: 'DeFi autopilot banker. Swaps, bridges, limit orders across chains.',
    score: 95,
    status: 'verified',
    vouched: 31.4,
    reviews: 156,
    contract: '0x22af33fe49fd1fa80c7149773dde5890d3c76f3b',
    twitter: 'bankrbot',
    logo: 'B',
    gradient: 'from-green-500 to-emerald-500',
    featured: true,
    launchPlatform: 'bankr',
    marketCap: '$88M'
  },
  {
    id: 'mamo',
    name: 'Mamo',
    handle: '@mamo',
    token: '$MAMO',
    category: 'DeFi',
    description: 'Chat-based DeFi simplifier. Staking, lending in Base app. Coinbase-backed.',
    score: 89,
    status: 'verified',
    vouched: 22.5,
    reviews: 78,
    contract: '0x7300b37dfdfab110d83290a29dfb31b1740219fe',
    twitter: 'mamo',
    logo: 'MA',
    gradient: 'from-lime-500 to-green-500',
    launchPlatform: 'other'
  },
  {
    id: 'antihunter',
    name: 'AntiHunter',
    handle: '@AntiHunter59823',
    token: '$ANTIHUNTER',
    category: 'Trading',
    description: 'Agentic AI VC investor. Investments, fee earning, buybacks.',
    score: 88,
    status: 'verified',
    vouched: 18.0,
    reviews: 54,
    contract: '0xe2f3fae4bc62e21826018364aa30ae45d430bb07',
    twitter: 'AntiHunter59823',
    logo: 'AH',
    gradient: 'from-red-500 to-orange-500',
    recentlyAdded: true,
    launchPlatform: 'other'
  },
  {
    id: 'clawnch',
    name: 'Clawnch Bot',
    handle: '@Clawnch_Bot',
    token: '$CLAWNCH',
    category: 'Infrastructure',
    description: 'Token launch agent. Fee generation, 8.6K+ launches. $1M+ in fees.',
    score: 87,
    status: 'verified',
    vouched: 15.5,
    reviews: 67,
    twitter: 'Clawnch_Bot',
    logo: 'CW',
    gradient: 'from-emerald-500 to-teal-500',
    launchPlatform: 'other'
  },
  {
    id: 'elsa',
    name: 'Hey Elsa AI',
    handle: '@HeyElsaAI',
    token: '$ELSA',
    category: 'DeFi',
    description: 'DeFi copilot. Staking, lending guidance, x402 payments.',
    score: 86,
    status: 'verified',
    vouched: 12.8,
    reviews: 52,
    contract: '0x80f994e39286c2c624ee9f647365c7dc1f4e3fbf',
    twitter: 'HeyElsaAI',
    logo: 'E',
    gradient: 'from-pink-500 to-rose-500',
    launchPlatform: 'bankr'
  },
  {
    id: 'griffin',
    name: 'Griffin AI',
    handle: '@Griffin_AI',
    token: '$GAIN',
    category: 'Trading',
    description: 'Transaction executor. Swaps, staking, agent societies.',
    score: 85,
    status: 'pending',
    vouched: 10.5,
    reviews: 43,
    twitter: 'Griffin_AI',
    logo: 'GR',
    gradient: 'from-amber-600 to-orange-500',
    launchPlatform: 'virtuals'
  },
  {
    id: 'wach',
    name: 'Wach AI',
    handle: '@Wach_AI',
    token: 'N/A',
    category: 'Analytics',
    description: 'DeFi risk analytics. x402 SDK, secure mandates, workflow automation.',
    score: 84,
    status: 'pending',
    vouched: 8.5,
    reviews: 38,
    twitter: 'Wach_AI',
    logo: 'W',
    gradient: 'from-yellow-500 to-orange-500',
    launchPlatform: 'bankr'
  },
  {
    id: 'moxie',
    name: 'Moxie',
    handle: '@moxie_xyz',
    token: '$MOXIE',
    category: 'DeFi',
    description: 'DeFi productivity assistant. Automation, tasks.',
    score: 83,
    status: 'pending',
    vouched: 9.2,
    reviews: 41,
    twitter: 'moxie_xyz',
    logo: 'MX',
    gradient: 'from-violet-500 to-purple-500',
    recentlyAdded: true,
    launchPlatform: 'other'
  },

  // ═══ TIER 3: SOCIAL & CONTENT AGENTS (21-40) ═══
  {
    id: 'luna',
    name: 'Luna by Virtuals',
    handle: '@luna_virtuals',
    token: '$LUNA',
    category: 'Social',
    description: 'On-chain AI companion. Interactions, governance, community-owned.',
    score: 94,
    status: 'pending',
    vouched: 65.0,
    reviews: 134,
    contract: '0x55cd6469f597452b5a7536e2cd98fde4c1247ee4',
    twitter: 'luna_virtuals',
    logo: 'LU',
    gradient: 'from-pink-500 to-rose-500',
    featured: true,
    launchPlatform: 'virtuals'
  },
  {
    id: 'game',
    name: 'GAME by Virtuals',
    handle: '@game_virtuals',
    token: '$GAME',
    category: 'Gaming',
    description: 'Gaming AI agent and ecosystem by Virtuals Protocol.',
    score: 93,
    status: 'pending',
    vouched: 101.2,
    reviews: 112,
    contract: '0x1c4cca7c5db003824208adda61bd749e55f463a3',
    twitter: 'game_virtuals',
    logo: 'GA',
    gradient: 'from-purple-500 to-pink-500',
    featured: true,
    launchPlatform: 'virtuals'
  },
  {
    id: 'vader',
    name: 'Vader AI',
    handle: '@Vader_AI_',
    token: '$VADER',
    category: 'Social',
    description: 'AI character agent. Social, metaverse applications, profit sharing.',
    score: 88,
    status: 'pending',
    vouched: 25.0,
    reviews: 67,
    twitter: 'Vader_AI_',
    logo: 'VA',
    gradient: 'from-gray-600 to-slate-800',
    launchPlatform: 'virtuals'
  },
  {
    id: 'beats',
    name: 'Beats on Base',
    handle: '@BeatsOnBase',
    token: '$BEATS',
    category: 'Creative',
    description: 'Music AI agent. Content creation, NFTs, event engagement.',
    score: 82,
    status: 'pending',
    vouched: 8.5,
    reviews: 45,
    twitter: 'BeatsOnBase',
    logo: 'BE',
    gradient: 'from-fuchsia-500 to-pink-500',
    launchPlatform: 'other'
  },
  {
    id: 'billy',
    name: 'Billy Bets',
    handle: '@AskBillyBets',
    token: '$BILLY',
    category: 'Gaming',
    description: 'Sports betting AI. Predictions, tips, social features.',
    score: 81,
    status: 'pending',
    vouched: 7.5,
    reviews: 38,
    twitter: 'AskBillyBets',
    logo: 'BI',
    gradient: 'from-green-600 to-emerald-500',
    launchPlatform: 'other'
  },
  {
    id: 'felix',
    name: 'Felix',
    handle: '@FelixCraftAI',
    token: '$FELIX',
    category: 'DeFi',
    description: 'Revenue-generating agent. Income from tasks, proven utility.',
    score: 80,
    status: 'pending',
    vouched: 6.5,
    reviews: 32,
    twitter: 'FelixCraftAI',
    logo: 'FE',
    gradient: 'from-orange-500 to-amber-500',
    launchPlatform: 'other'
  },
  {
    id: 'kellyclaude',
    name: 'KellyClaude',
    handle: '@KellyClaudeAI',
    token: '$KELLYCLAUDE',
    category: 'Creative',
    description: 'AI agent for crafts. Creative tasks, strong charts.',
    score: 79,
    status: 'pending',
    vouched: 5.5,
    reviews: 28,
    contract: '0x50d2280441372486beecdd328c1854743ebacb07',
    twitter: 'KellyClaudeAI',
    logo: 'KC',
    gradient: 'from-orange-500 to-red-500',
    recentlyAdded: true,
    launchPlatform: 'other'
  },
  {
    id: 'ribbita',
    name: 'Ribbita by Virtuals',
    handle: '@ribbita_virtuals',
    token: '$TIBBIR',
    category: 'Social',
    description: 'Meme-powered AI. Personality-driven interactions.',
    score: 87,
    status: 'pending',
    vouched: 47.1,
    reviews: 89,
    twitter: 'ribbita_virtuals',
    logo: 'RI',
    gradient: 'from-green-400 to-lime-500',
    launchPlatform: 'virtuals',
    marketCap: '$132M'
  },

  // ═══ TIER 4: SPECIALIZED & EMERGING (41-70) ═══
  {
    id: 'heyanon',
    name: 'HeyAnon',
    handle: '@heyanon_ai',
    token: '$ANON',
    category: 'Social',
    description: 'Anonymous AI social agent for private interactions.',
    score: 86,
    status: 'pending',
    vouched: 15.5,
    reviews: 64,
    contract: '0x79bbf4508b1391af3a0f4b30bb5fc4aa9ab0e07c',
    twitter: 'heyanon_ai',
    logo: 'AN',
    gradient: 'from-gray-500 to-slate-500',
    launchPlatform: 'other'
  },
  {
    id: 'recall',
    name: 'Recall',
    handle: '@recallnet',
    token: '$RECALL',
    category: 'Analytics',
    description: 'Network recall agent. Data retrieval, memory, performance boost.',
    score: 85,
    status: 'pending',
    vouched: 12.0,
    reviews: 52,
    contract: '0x1f16e03c1a5908818f47f6ee7bb16690b40d0671',
    twitter: 'recallnet',
    logo: 'RE',
    gradient: 'from-teal-500 to-green-500',
    launchPlatform: 'other'
  },
  {
    id: 'cookie',
    name: 'Cookie',
    handle: '@cookiedotfun',
    token: '$COOKIE',
    category: 'Analytics',
    description: 'AI agent data and indexing platform.',
    score: 84,
    status: 'pending',
    vouched: 10.5,
    reviews: 45,
    contract: '0xc0041ef357b183448b235a8ea73ce4e4ec8c265f',
    twitter: 'cookiedotfun',
    logo: 'CO',
    gradient: 'from-yellow-600 to-amber-500',
    launchPlatform: 'other'
  },
  {
    id: 'aion',
    name: 'Aion 5100',
    handle: '@aion5100',
    token: '$AION',
    category: 'Infrastructure',
    description: 'Advanced AI agent. Workflows, automation.',
    score: 83,
    status: 'pending',
    vouched: 7.5,
    reviews: 34,
    contract: '0xfc48314ad4ad5bd36a84e8307b86a68a01d95d9c',
    twitter: 'aion5100',
    logo: 'AI',
    gradient: 'from-violet-500 to-purple-500',
    launchPlatform: 'other'
  },
  {
    id: 'wayfinder',
    name: 'Wayfinder',
    handle: '@wayfinder_ai',
    token: '$PROMPT',
    category: 'Infrastructure',
    description: 'AI agent navigation and prompt routing.',
    score: 82,
    status: 'pending',
    vouched: 11.0,
    reviews: 48,
    contract: '0x30c7235866872213f68cb1f08c37cb9eccb93452',
    twitter: 'wayfinder_ai',
    logo: 'WF',
    gradient: 'from-cyan-500 to-blue-500',
    launchPlatform: 'other'
  },
  {
    id: 'openserv',
    name: 'OpenServ',
    handle: '@openserv_ai',
    token: '$SERV',
    category: 'Infrastructure',
    description: 'Open service infrastructure for AI agents.',
    score: 81,
    status: 'pending',
    vouched: 6.5,
    reviews: 29,
    contract: '0x5576d6ed9181f2225aff5282ac0ed29f755437ea',
    twitter: 'openserv_ai',
    logo: 'OS',
    gradient: 'from-emerald-500 to-teal-500',
    launchPlatform: 'other'
  },
  {
    id: 'fai',
    name: 'FAI',
    handle: '@fai_agent',
    token: '$FAI',
    category: 'DeFi',
    description: 'Financial AI agent for DeFi operations.',
    score: 80,
    status: 'pending',
    vouched: 4.0,
    reviews: 17,
    contract: '0xb33ff54b9f7242ef1593d2c9bcd8f9df46c77935',
    twitter: 'fai_agent',
    logo: 'FA',
    gradient: 'from-blue-600 to-indigo-500',
    launchPlatform: 'other'
  },
  {
    id: 'ava',
    name: 'Ava AI',
    handle: '@ava_ai',
    token: '$AVA',
    category: 'Social',
    description: 'Conversational AI agent with advanced capabilities.',
    score: 79,
    status: 'pending',
    vouched: 3.5,
    reviews: 15,
    contract: '0x80ca9edce4583b8043351a1046f18244b24ef869',
    twitter: 'ava_ai',
    logo: 'AV',
    gradient: 'from-fuchsia-500 to-pink-500',
    recentlyAdded: true,
    launchPlatform: 'other'
  },
  {
    id: 'gaix',
    name: 'GAIX',
    handle: '@gaix_ai',
    token: '$GAIX',
    category: 'Gaming',
    description: 'Gaming and analytics AI infrastructure.',
    score: 78,
    status: 'pending',
    vouched: 3.0,
    reviews: 13,
    contract: '0x07279154860356839e33f59123d25b857b07eb07',
    twitter: 'gaix_ai',
    logo: 'GX',
    gradient: 'from-purple-600 to-violet-500',
    launchPlatform: 'other'
  },
  {
    id: 'rain',
    name: 'Rain Coin',
    handle: '@rain_ai',
    token: '$RAIN',
    category: 'DeFi',
    description: 'DeFi yield and rain distribution agent.',
    score: 77,
    status: 'pending',
    vouched: 2.5,
    reviews: 11,
    contract: '0x4e21eabf4fc4cf66f10a93395e4b0e2438de81a6',
    twitter: 'rain_ai',
    logo: 'RA',
    gradient: 'from-sky-500 to-blue-500',
    recentlyAdded: true,
    launchPlatform: 'other'
  },
  {
    id: 'acolyt',
    name: 'Acolyt AI',
    handle: '@AcolytAI',
    token: '$ACOLYT',
    category: 'Analytics',
    description: 'AI analysis. Trends, assessments.',
    score: 76,
    status: 'pending',
    vouched: 4.5,
    reviews: 22,
    twitter: 'AcolytAI',
    logo: 'AC',
    gradient: 'from-indigo-500 to-purple-500',
    launchPlatform: 'virtuals'
  },
  {
    id: 'ai16z',
    name: 'ai16z',
    handle: '@ai16zdao',
    token: '$AI16Z',
    category: 'Trading',
    description: 'Investment DAO. AI-driven token buying. Marc Andreessen model.',
    score: 85,
    status: 'pending',
    vouched: 28.5,
    reviews: 87,
    twitter: 'ai16zdao',
    logo: 'A1',
    gradient: 'from-red-500 to-orange-500',
    launchPlatform: 'other'
  },
  {
    id: 'freysa',
    name: 'Freysa AI',
    handle: '@freysa_ai',
    token: '$FAI',
    category: 'Infrastructure',
    description: 'Sovereign AI agent. Wallet control, evolving capabilities.',
    score: 84,
    status: 'pending',
    vouched: 7.3,
    reviews: 29,
    twitter: 'freysa_ai',
    logo: 'F',
    gradient: 'from-violet-500 to-purple-500',
    launchPlatform: 'other'
  },
  {
    id: 'doppel',
    name: 'Doppel',
    handle: '@doppel_ai',
    token: '$DOPPEL',
    category: 'Creative',
    description: '3D world builder. Roblox for agents. Ex-DEX team.',
    score: 78,
    status: 'pending',
    vouched: 5.5,
    reviews: 24,
    twitter: 'doppel_ai',
    logo: 'DO',
    gradient: 'from-cyan-600 to-teal-500',
    recentlyAdded: true,
    launchPlatform: 'other'
  },
  {
    id: 'origintrial',
    name: 'OriginTrail',
    handle: '@Origin_Trail',
    token: '$TRAC',
    category: 'Infrastructure',
    description: 'Knowledge graph for AI. Verifiable data, enterprise use.',
    score: 86,
    status: 'pending',
    vouched: 53.6,
    reviews: 98,
    twitter: 'Origin_Trail',
    logo: 'OT',
    gradient: 'from-blue-500 to-purple-500',
    launchPlatform: 'other',
    marketCap: '$150M'
  },
  {
    id: 'basedagent',
    name: 'Based Agent',
    handle: '@BasedAgentAI',
    token: '$BASED',
    category: 'Infrastructure',
    description: 'General agent for tasks. Virtuals-based.',
    score: 75,
    status: 'pending',
    vouched: 4.0,
    reviews: 18,
    twitter: 'BasedAgentAI',
    logo: 'BA',
    gradient: 'from-blue-600 to-indigo-600',
    launchPlatform: 'virtuals'
  },
  {
    id: 'ritual',
    name: 'Ritual',
    handle: '@ritualnet',
    token: 'N/A',
    category: 'Infrastructure',
    description: 'Base layer for AI. Off-chain/on-chain developer platform.',
    score: 82,
    status: 'pending',
    vouched: 12.0,
    reviews: 45,
    twitter: 'ritualnet',
    logo: 'RT',
    gradient: 'from-slate-600 to-gray-700',
    launchPlatform: 'other'
  },
  {
    id: 'kudai',
    name: 'Kudai',
    handle: '@Kudai_IO',
    token: '$KUDAI',
    category: 'DeFi',
    description: 'Real-yield focused automation agent.',
    score: 73,
    status: 'pending',
    vouched: 1.5,
    reviews: 11,
    twitter: 'Kudai_IO',
    logo: 'K',
    gradient: 'from-lime-500 to-green-500',
    launchPlatform: 'bankr'
  },
  {
    id: 'zerebro',
    name: '0xZerebro',
    handle: '@0xzerebro',
    token: '$ZEREBRO',
    category: 'Creative',
    description: 'Cross-chain artist and content creation agent.',
    score: 81,
    status: 'pending',
    vouched: 4.8,
    reviews: 35,
    twitter: '0xzerebro',
    logo: 'Z',
    gradient: 'from-red-500 to-pink-500',
    launchPlatform: 'other'
  },
  {
    id: 'louder',
    name: 'Louder on Base',
    handle: '@louderonbase',
    token: '$LOUDER',
    category: 'Creative',
    description: 'On-chain musician AI agent.',
    score: 76,
    status: 'pending',
    vouched: 2.1,
    reviews: 18,
    twitter: 'louderonbase',
    logo: 'L',
    gradient: 'from-amber-500 to-yellow-500',
    recentlyAdded: true,
    launchPlatform: 'bankr'
  },
  {
    id: 'simulacrum',
    name: 'Simulacrum',
    handle: '@SimulacrumIO',
    token: '$SIM',
    category: 'Infrastructure',
    description: 'Tweet-to-agent deployment platform.',
    score: 74,
    status: 'pending',
    vouched: 1.9,
    reviews: 14,
    twitter: 'SimulacrumIO',
    logo: 'SI',
    gradient: 'from-cyan-500 to-blue-500',
    recentlyAdded: true,
    launchPlatform: 'other'
  },
  {
    id: 'holoworld',
    name: 'HoloWorld AI',
    handle: '@HoloworldAI',
    token: '$HOLO',
    category: 'Creative',
    description: 'Character and storytelling AI engine.',
    score: 71,
    status: 'pending',
    vouched: 1.2,
    reviews: 9,
    twitter: 'HoloworldAI',
    logo: 'H',
    gradient: 'from-fuchsia-500 to-pink-500',
    recentlyAdded: true,
    launchPlatform: 'bankr'
  },
  {
    id: 'almanax',
    name: 'Almanax AI',
    handle: '@AlmanaxAI',
    token: '$ALMANAX',
    category: 'Security',
    description: 'Blockchain vulnerability-finding agent.',
    score: 78,
    status: 'pending',
    vouched: 3.1,
    reviews: 16,
    twitter: 'AlmanaxAI',
    logo: 'A',
    gradient: 'from-rose-500 to-red-500',
    launchPlatform: 'bankr'
  },
  {
    id: 'morpheus',
    name: 'Morpheus AIs',
    handle: '@MorpheusAIs',
    token: '$MOR',
    category: 'Infrastructure',
    description: 'Decentralized AI infrastructure network.',
    score: 82,
    status: 'pending',
    vouched: 5.5,
    reviews: 33,
    twitter: 'MorpheusAIs',
    logo: 'MO',
    gradient: 'from-green-600 to-emerald-500',
    launchPlatform: 'other'
  },
  {
    id: 'clanker',
    name: 'Clanker',
    handle: '@clanker_world',
    token: '$CLANKER',
    category: 'Infrastructure',
    description: 'Token issuance infrastructure for autonomous agent deployments.',
    score: 90,
    status: 'pending',
    vouched: 18.2,
    reviews: 67,
    contract: '0x1bc0c42215582d5a085795f3e8d98e39f4e9d6b0',
    twitter: 'clanker_world',
    logo: 'C',
    gradient: 'from-purple-500 to-pink-500',
    featured: true,
    launchPlatform: 'clanker'
  },
  {
    id: 'lobsterxbt',
    name: 'LobsterXBT AI',
    handle: '@LOBSTERXBTAI',
    token: '$LOBSTER',
    category: 'Analytics',
    description: 'Market tracking and on-chain data agent.',
    score: 77,
    status: 'pending',
    vouched: 2.8,
    reviews: 19,
    twitter: 'LOBSTERXBTAI',
    logo: 'LX',
    gradient: 'from-red-600 to-orange-500',
    launchPlatform: 'bankr'
  },
  {
    id: 'clawdbot',
    name: 'Clawdbot',
    handle: '@clawdbotatg',
    token: '$CLAWD',
    category: 'Infrastructure',
    description: 'Multi-agent QA and testing. App performance checks.',
    score: 88,
    status: 'pending',
    vouched: 12.8,
    reviews: 56,
    twitter: 'clawdbotatg',
    logo: 'CB',
    gradient: 'from-orange-500 to-red-500',
    launchPlatform: 'other'
  },
  {
    id: 'debtreliefbot',
    name: 'DebtReliefBot',
    handle: '@debtreliefbot',
    token: '$DRB',
    category: 'DeFi',
    description: 'Debt management and financial aid agent.',
    score: 75,
    status: 'pending',
    vouched: 4.3,
    reviews: 21,
    twitter: 'debtreliefbot',
    logo: 'DR',
    gradient: 'from-green-500 to-teal-500',
    launchPlatform: 'bankr',
    marketCap: '$12M'
  },
  {
    id: 'botcoin',
    name: 'Botcoin',
    handle: '@botcoin',
    token: '$BOTCOIN',
    category: 'Infrastructure',
    description: 'Bot economy utility token. High volume.',
    score: 74,
    status: 'pending',
    vouched: 3.8,
    reviews: 18,
    twitter: 'botcoin',
    logo: 'BC',
    gradient: 'from-blue-500 to-cyan-500',
    launchPlatform: 'bankr'
  },
  {
    id: 'eternalai',
    name: 'Eternal AI',
    handle: '@EternalAI_',
    token: 'N/A',
    category: 'Creative',
    description: 'Privacy AI studio. Image/video generation. 5.3K agents on Base.',
    score: 80,
    status: 'pending',
    vouched: 8.5,
    reviews: 42,
    twitter: 'EternalAI_',
    logo: 'EA',
    gradient: 'from-indigo-600 to-purple-600',
    launchPlatform: 'other'
  },
  {
    id: 'loomlay',
    name: 'Loomlay',
    handle: '@loomlay_ai',
    token: '$LAY',
    category: 'Infrastructure',
    description: 'No-code builder for agents. Plugins, easy creation.',
    score: 76,
    status: 'pending',
    vouched: 3.2,
    reviews: 16,
    twitter: 'loomlay_ai',
    logo: 'LL',
    gradient: 'from-pink-500 to-rose-500',
    recentlyAdded: true,
    launchPlatform: 'other'
  },
  {
    id: 'superchamps',
    name: 'SuperChamps',
    handle: '@SuperChampsHQ',
    token: '$CHAMP',
    category: 'Gaming',
    description: 'Sports agent. Gaming, bets, high engagement.',
    score: 75,
    status: 'pending',
    vouched: 2.8,
    reviews: 14,
    twitter: 'SuperChampsHQ',
    logo: 'SC',
    gradient: 'from-amber-500 to-orange-500',
    launchPlatform: 'other'
  },
  {
    id: 'santavirtuals',
    name: 'Santa Virtuals',
    handle: '@santavirtuals',
    token: '$SANTA',
    category: 'Social',
    description: 'Holiday-themed AI. Fun, seasonal events.',
    score: 72,
    status: 'pending',
    vouched: 1.8,
    reviews: 12,
    twitter: 'santavirtuals',
    logo: 'SA',
    gradient: 'from-red-500 to-green-500',
    recentlyAdded: true,
    launchPlatform: 'virtuals'
  },
]

// Helper functions
export const getFeaturedAgents = () => agents.filter(a => a.featured)
export const getRecentlyAdded = () => agents.filter(a => a.recentlyAdded)
export const getVerifiedAgents = () => agents.filter(a => a.status === 'verified')
export const getAgentsByCategory = (cat: string) => agents.filter(a => a.category === cat)
export const getAgentById = (id: string) => agents.find(a => a.id === id)
export const getTotalVouched = () => agents.reduce((sum, a) => sum + a.vouched, 0)
export const getTotalVouchedUSD = () => getTotalVouched() * ETH_PRICE
export const getVerifiedCount = () => agents.filter(a => a.status === 'verified').length
